"""first commit

Revision ID: 58c0bf6e004b
Revises: 
Create Date: 2022-04-12 01:06:33.466767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c0bf6e004b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_api',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('path', sa.String(length=50), nullable=False, comment='api接口uri'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='api接口方法'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='api名称描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='后台权限表'
    )
    op.create_index(op.f('ix_sys_api_change_by_id'), 'sys_api', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_api_create_by_id'), 'sys_api', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_api_deleted_by_id'), 'sys_api', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_api_state'), 'sys_api', ['state'], unique=False)
    op.create_table('sys_doc_while_list',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('while_ip', sa.String(length=30), nullable=True, comment='允许ip'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sys_doc_while_list_change_by_id'), 'sys_doc_while_list', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_doc_while_list_create_by_id'), 'sys_doc_while_list', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_doc_while_list_deleted_by_id'), 'sys_doc_while_list', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_doc_while_list_state'), 'sys_doc_while_list', ['state'], unique=False)
    op.create_table('sys_login_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('account', sa.String(length=30), nullable=True, comment='登陆账号'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('login_ip', sa.String(length=30), nullable=True, comment='操作ip'),
    sa.Column('browser', sa.String(length=300), nullable=True, comment='浏览器'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='是否成功登陆'),
    sa.Column('access_token', sa.String(length=50), nullable=True, comment='访问token'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sys_login_log_change_by_id'), 'sys_login_log', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_login_log_create_by_id'), 'sys_login_log', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_login_log_deleted_by_id'), 'sys_login_log', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_login_log_state'), 'sys_login_log', ['state'], unique=False)
    op.create_table('sys_menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级菜单id, 0表示最顶级菜单'),
    sa.Column('menu_name', sa.String(length=30), nullable=False, comment='菜单名称'),
    sa.Column('menu_code', sa.String(length=100), nullable=False, comment='组件路径(前端请求文件的路径里),目录可填Layout'),
    sa.Column('menu_url', sa.String(length=100), nullable=False, comment='权限标识,即标识每一个操作权限'),
    sa.Column('menu_icon', sa.String(length=100), nullable=True, comment='图标，meta里面的icon'),
    sa.Column('menu_type', sa.SmallInteger(), nullable=True, comment='资源类型,0为目录、1为菜单、2为按钮'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_sys_menu_change_by_id'), 'sys_menu', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_create_by_id'), 'sys_menu', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_deleted_by_id'), 'sys_menu', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_state'), 'sys_menu', ['state'], unique=False)
    op.create_table('sys_operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('operation_url', sa.String(length=500), nullable=True, comment='操作链接'),
    sa.Column('request_body', sa.JSON(), nullable=True, comment='请求体'),
    sa.Column('is_doc', sa.Boolean(), nullable=True, comment='是否是doc操作'),
    sa.Column('ip', sa.String(length=300), nullable=True, comment='操作ip'),
    sa.Column('browser', sa.String(length=300), nullable=True, comment='浏览器'),
    sa.Column('account', sa.String(length=50), nullable=True, comment='操作用户'),
    sa.Column('access_token', sa.String(length=50), nullable=True, comment='访问token'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sys_operation_log_change_by_id'), 'sys_operation_log', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_create_by_id'), 'sys_operation_log', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_deleted_by_id'), 'sys_operation_log', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_state'), 'sys_operation_log', ['state'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('role_name', sa.String(length=30), nullable=False, comment='角色名称'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='后台角色表'
    )
    op.create_index(op.f('ix_sys_role_change_by_id'), 'sys_role', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_create_by_id'), 'sys_role', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_deleted_by_id'), 'sys_role', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_state'), 'sys_role', ['state'], unique=False)
    op.create_table('sys_role_menu_rel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色id'),
    sa.Column('menu_id', sa.Integer(), nullable=True, comment='菜单id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='角色菜单表'
    )
    op.create_index(op.f('ix_sys_role_menu_rel_change_by_id'), 'sys_role_menu_rel', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_rel_create_by_id'), 'sys_role_menu_rel', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_rel_deleted_by_id'), 'sys_role_menu_rel', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_rel_menu_id'), 'sys_role_menu_rel', ['menu_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_rel_role_id'), 'sys_role_menu_rel', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_rel_state'), 'sys_role_menu_rel', ['state'], unique=False)
    op.create_table('sys_role_permission_rel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色id'),
    sa.Column('api_id', sa.Integer(), nullable=True, comment='Api_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='角色API权限表'
    )
    op.create_index(op.f('ix_sys_role_permission_rel_api_id'), 'sys_role_permission_rel', ['api_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_rel_change_by_id'), 'sys_role_permission_rel', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_rel_create_by_id'), 'sys_role_permission_rel', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_rel_deleted_by_id'), 'sys_role_permission_rel', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_rel_role_id'), 'sys_role_permission_rel', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_rel_state'), 'sys_role_permission_rel', ['state'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('account', sa.String(length=40), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=80), nullable=False, comment='密码'),
    sa.Column('user_name', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('is_super', sa.SmallInteger(), nullable=True, comment='超级管理员'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='手机号码'),
    sa.Column('email', sa.String(length=30), nullable=True, comment='邮箱'),
    sa.Column('roles', sa.JSON(), nullable=False, comment='角色id'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='后台用户表'
    )
    op.create_index(op.f('ix_sys_user_change_by_id'), 'sys_user', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_create_by_id'), 'sys_user', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_deleted_by_id'), 'sys_user', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_sys_user_state'), 'sys_user', ['state'], unique=False)
    op.create_table('weekly_project',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('name', sa.String(length=40), nullable=False, comment='项目名称'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='周报项目表'
    )
    op.create_index(op.f('ix_weekly_project_change_by_id'), 'weekly_project', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_project_create_by_id'), 'weekly_project', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_project_deleted_by_id'), 'weekly_project', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_project_state'), 'weekly_project', ['state'], unique=False)
    op.create_table('weekly_report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('type_id', sa.Integer(), nullable=True, comment='类型id'),
    sa.Column('applicant', sa.String(length=40), nullable=True, comment='申请人'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目id'),
    sa.Column('operation_text', sa.String(length=500), nullable=True, comment='操作内容'),
    sa.Column('result', sa.String(length=40), nullable=True, comment='处理结果'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='周报表'
    )
    op.create_index(op.f('ix_weekly_report_change_by_id'), 'weekly_report', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_create_by_id'), 'weekly_report', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_deleted_by_id'), 'weekly_report', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_state'), 'weekly_report', ['state'], unique=False)
    op.create_table('weekly_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('state', sa.SmallInteger(), nullable=True, comment='状态值, 0为已删除, 1为正常, 2为锁定'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('create_by_id', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('last_change_time', sa.DateTime(), nullable=True, comment='最后修改的时间'),
    sa.Column('change_by_id', sa.BigInteger(), nullable=True, comment='最后修改者ID'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by_id', sa.BigInteger(), nullable=True, comment='删除者id'),
    sa.Column('name', sa.String(length=40), nullable=False, comment='类别名称'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='周报类型表'
    )
    op.create_index(op.f('ix_weekly_type_change_by_id'), 'weekly_type', ['change_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_type_create_by_id'), 'weekly_type', ['create_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_type_deleted_by_id'), 'weekly_type', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_weekly_type_state'), 'weekly_type', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_type_state'), table_name='weekly_type')
    op.drop_index(op.f('ix_weekly_type_deleted_by_id'), table_name='weekly_type')
    op.drop_index(op.f('ix_weekly_type_create_by_id'), table_name='weekly_type')
    op.drop_index(op.f('ix_weekly_type_change_by_id'), table_name='weekly_type')
    op.drop_table('weekly_type')
    op.drop_index(op.f('ix_weekly_report_state'), table_name='weekly_report')
    op.drop_index(op.f('ix_weekly_report_deleted_by_id'), table_name='weekly_report')
    op.drop_index(op.f('ix_weekly_report_create_by_id'), table_name='weekly_report')
    op.drop_index(op.f('ix_weekly_report_change_by_id'), table_name='weekly_report')
    op.drop_table('weekly_report')
    op.drop_index(op.f('ix_weekly_project_state'), table_name='weekly_project')
    op.drop_index(op.f('ix_weekly_project_deleted_by_id'), table_name='weekly_project')
    op.drop_index(op.f('ix_weekly_project_create_by_id'), table_name='weekly_project')
    op.drop_index(op.f('ix_weekly_project_change_by_id'), table_name='weekly_project')
    op.drop_table('weekly_project')
    op.drop_index(op.f('ix_sys_user_state'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_deleted_by_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_by_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_change_by_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_permission_rel_state'), table_name='sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_permission_rel_role_id'), table_name='sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_permission_rel_deleted_by_id'), table_name='sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_permission_rel_create_by_id'), table_name='sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_permission_rel_change_by_id'), table_name='sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_permission_rel_api_id'), table_name='sys_role_permission_rel')
    op.drop_table('sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_state'), table_name='sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_role_id'), table_name='sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_menu_id'), table_name='sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_deleted_by_id'), table_name='sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_create_by_id'), table_name='sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_menu_rel_change_by_id'), table_name='sys_role_menu_rel')
    op.drop_table('sys_role_menu_rel')
    op.drop_index(op.f('ix_sys_role_state'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_deleted_by_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_create_by_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_change_by_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_operation_log_state'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_deleted_by_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_create_by_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_change_by_id'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_index(op.f('ix_sys_menu_state'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_deleted_by_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_create_by_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_change_by_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_login_log_state'), table_name='sys_login_log')
    op.drop_index(op.f('ix_sys_login_log_deleted_by_id'), table_name='sys_login_log')
    op.drop_index(op.f('ix_sys_login_log_create_by_id'), table_name='sys_login_log')
    op.drop_index(op.f('ix_sys_login_log_change_by_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_doc_while_list_state'), table_name='sys_doc_while_list')
    op.drop_index(op.f('ix_sys_doc_while_list_deleted_by_id'), table_name='sys_doc_while_list')
    op.drop_index(op.f('ix_sys_doc_while_list_create_by_id'), table_name='sys_doc_while_list')
    op.drop_index(op.f('ix_sys_doc_while_list_change_by_id'), table_name='sys_doc_while_list')
    op.drop_table('sys_doc_while_list')
    op.drop_index(op.f('ix_sys_api_state'), table_name='sys_api')
    op.drop_index(op.f('ix_sys_api_deleted_by_id'), table_name='sys_api')
    op.drop_index(op.f('ix_sys_api_create_by_id'), table_name='sys_api')
    op.drop_index(op.f('ix_sys_api_change_by_id'), table_name='sys_api')
    op.drop_table('sys_api')
    # ### end Alembic commands ###
